### ISSUE TITLE
Add CONTRIBUTION.md file

### ISSUE THREAD

**Issue by muthuannamalai12** [infiniteoverflow/Flutter-Tutorial-App#12]
I would like to add a CONTRIBUTING.mdfile which will contain all contributing guidelines and all git workflow so that all newbies or beginners and even experts can look into it and also the contributors will understand the workflow

**Comment by muthuannamalai12** [comment]
I would love to work on it as a part of Cross Woc. Kindly assign it to me.

**Comment by infiniteoverflow** [comment]
Yes sure add the file. Just name it CONTRIBUTING_GUIDELINES.md , as CONTRIBUTING.md has to be kept for CrossWOC purpose.

**Comment by muthuannamalai12** [comment]
> Yes sure add the file. Just name it CONTRIBUTING_GUIDELINES.md , as CONTRIBUTING.md has to be kept for CrossWOC purpose.

Ok
