### ISSUE TITLE
Add HomePage Screen

### ISSUE THREAD

**Issue by infiniteoverflow** [infiniteoverflow/Flutter-Tutorial-App#16]
The app needs an HomeScreen which has to be shown everytime the user logs in.

<img src="https://user-images.githubusercontent.com/40236624/107870755-357c1580-6ec1-11eb-9950-983ea0e42158.png" height=400 width=200/>

The assets are available in the `assets/icons` folder. We will take this as a tentative ui , later we will update with a better ui !!

- Add this screen to the `screens` folder inside lib.
- Attach a Navigation drawer on clicking the drawer icon
- Redirect to a blank screen on clicking the accounts icon. Name the screen file as `accounts.dart` and add the file to the `screens` folder.

**Comment by Saransh-cpp** [comment]
I'd like to take up this issue.

Questions
1. The images need to be clickable right?
2. The drawer will be a blank default flutter App drawer or are you looking for something else?

**Comment by infiniteoverflow** [comment]
Yes , the images are clickable , for the drawer image add a drawer() , and for profile image add a route to a new screen. For the rest two images , let the onTap be empty.
