### ISSUE TITLE
Add Splash Screen

### ISSUE THREAD

**Issue by infiniteoverflow** [infiniteoverflow/Flutter-Tutorial-App#2]
<img width="281" alt="Screenshot 2021-02-12 at 3 31 15 PM" src="https://user-images.githubusercontent.com/40236624/107754342-5a4c7d80-6d47-11eb-9de7-5d282d6d0175.png">

We need to show a screen similar to this to the user every time he opens the app.

**Comment by muthuannamalai12** [comment]
I would love to work on this issue as a part of Cross Woc. Kindly assign me this issue.

**Comment by infiniteoverflow** [comment]
@muthuannamalai12 At max i can assign you 2 issues at a time. Work on the previous ones , and later if no one else comments on this , i will assign it to u.

**Comment by muthuannamalai12** [comment]
> @muthuannamalai12 At max i can assign you 2 issues at a time. Work on the previous ones , and later if no one else comments on this , i will assign it to u.

Ok. Thanks

**Comment by hemangdtu** [comment]
Hello, I would like to work on this issue. Kindly assign it to me.

**Comment by avishmehta68710** [comment]
Hi i would like to work on this issue

**Comment by infiniteoverflow** [comment]
@hemangdtu Assigning you.

@avishmehta68710 We will have more issues to work on , so dont worry. Issues are assigned on a First Come First Serve basis.
