### ISSUE TITLE
Add a GitHub action to auto-assign Mentors for every PR 

### ISSUE THREAD

**Issue by muthuannamalai12** [infiniteoverflow/Flutter-Tutorial-App#24]
I would like to add a GitHub action to auto-assign mentors for every PR. It sometimes becomes hectic for the mentors to take a look at all the Projects for the PRs made by the Contributors. This action would give a nice notification about reviewing the pr and make things pretty easy for the mentor. It would automatically ask for reviews by the mentors on every pr created.

Demo :
![auto assign](https://user-images.githubusercontent.com/64524822/108363403-e44e8780-721a-11eb-96ff-ac4d8338e9b4.png)

**Comment by muthuannamalai12** [comment]
I would love to work on this issue as a part of Cross-Woc. Kindly assign it to me

**Comment by infiniteoverflow** [comment]
Thanks @muthuannamalai12 , but we currently dont have any mentors assigned for this project other than me , so this wont be appropriate at the moment. Later i will let u know when we need it. 

So currently i will be closing this issue.

**Comment by muthuannamalai12** [comment]
> Thanks @muthuannamalai12 , but we currently dont have any mentors assigned for this project other than me , so this wont be appropriate at the moment. Later i will let u know when we need it.
> 
> So currently i will be closing this issue.

Ok. Thank You
