### ISSUE TITLE
Update README : Lets make the tagline even catchier !!

### ISSUE THREAD

**Issue by infiniteoverflow** [infiniteoverflow/Flutter-Tutorial-App#4]
In the README.md file, we have a basic intro text given. Let's make it even catchier !! You are welcome to suggest a better tagline.

**Comment by 96RadhikaJadhav** [comment]
@infiniteoverflow How about this -> We know you love Flutter, isn't it? And that's why you are here! How about using your interest in building an app which can help people learn flutter!!

You must have heard about DartPad right? So how about building something like that? And that too in an app!!

**Comment by 96RadhikaJadhav** [comment]
@infiniteoverflow I'm a crossWoc participant and would like to create a PR, if you liked my suggestion for the tagline.

**Comment by infiniteoverflow** [comment]
Yess , sounds great !! The coding period starts tomorrow, so I will assign u the issue by midnight.

**Comment by 96RadhikaJadhav** [comment]
@infiniteoverflow Should I create 2 issues each for adding PR template and issue template? Or else you can create it and assign those to me. I would like to work on it too.

**Comment by infiniteoverflow** [comment]
I'm currently working on those two. It's almost done.
Anyways thanks for mentioning that.

**Comment by 96RadhikaJadhav** [comment]
> I'm currently working on those two. It's almost done.
> Anyways thanks for mentioning that.

Okay, no problem. Thank You!

**Comment by infiniteoverflow** [comment]
@96RadhikaJadhav You can go ahead !!
