### ISSUE TITLE
Docs: Non-clickable link in README.md

### ISSUE THREAD

**Issue by Saransh-cpp** [infiniteoverflow/Flutter-Tutorial-App#8]
1. The discord link in the README is not clickable. Something like [this](https://discord.com/invite/uatbc8uhtq) should be done.

Easy one, I would like to work on this.

**Comment by infiniteoverflow** [comment]
Sure @Saransh-cpp go ahead. I kind of made a mistake there.

**Comment by Saransh-cpp** [comment]
I think I made a mistake above by creating a PR in my own repo because I edited the README file on GitHub itself. Made the correct PR now! The issue is closed somehow, sorry for the inconvenience caused:)
